name: Telegram Trading Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # 수동 실행 가능
  schedule:
    - cron: '*/30 * * * *'  # 30분마다 실행

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run Telegram Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        ALLOWED_CHANNEL_ID: ${{ secrets.ALLOWED_CHANNEL_ID }}
        ALLOWED_USER_IDS: ${{ secrets.ALLOWED_USER_IDS }}
        EXCHANGE_API_KEY: ${{ secrets.EXCHANGE_API_KEY }}
        EXCHANGE_SECRET: ${{ secrets.EXCHANGE_SECRET }}
        EXCHANGE_PASSPHRASE: ${{ secrets.EXCHANGE_PASSPHRASE }}
      run: |
        python bot_runner.py 